apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
    env: dev
  namespace: shyam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo-pod
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        env:
        - name: "USERNAME"
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: username
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: mypvc