apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: shyam
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: "ebs-sc"