{{- if .Values.deploy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: yoyo
        image: nginx
{{- end }}
