{{- if .Values.deploy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        env: {{ .Values.environment }}
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
{{- end }}



































